// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChhZpsM4GU9XidNfzbqFlgtgmVSnvJft4',
    appId: '1:42604918668:web:18558b556d24fb6c1d48a9',
    messagingSenderId: '42604918668',
    projectId: 'clippy001-d7445',
    authDomain: 'clippy001-d7445.firebaseapp.com',
    databaseURL: 'https://clippy001-d7445-default-rtdb.firebaseio.com',
    storageBucket: 'clippy001-d7445.appspot.com',
    measurementId: 'G-RYBENBG1LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0Mx0GNm89yEJiC0phKp-YMykaTvr_0U',
    appId: '1:42604918668:android:c9e17ec8d626bea71d48a9',
    messagingSenderId: '42604918668',
    projectId: 'clippy001-d7445',
    databaseURL: 'https://clippy001-d7445-default-rtdb.firebaseio.com',
    storageBucket: 'clippy001-d7445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdu3UwExYlnu6LDMZcqQ2iMGUOfQxMBtE',
    appId: '1:42604918668:ios:6d148cba7e08ee711d48a9',
    messagingSenderId: '42604918668',
    projectId: 'clippy001-d7445',
    databaseURL: 'https://clippy001-d7445-default-rtdb.firebaseio.com',
    storageBucket: 'clippy001-d7445.appspot.com',
    androidClientId: '42604918668-0ehqg09in2ufnfb2j1vgk5oe7a1gkrr8.apps.googleusercontent.com',
    iosClientId: '42604918668-f10m30ou536mutrdle1pcnuvq205qnh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.clippy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdu3UwExYlnu6LDMZcqQ2iMGUOfQxMBtE',
    appId: '1:42604918668:ios:5be7b4646a85c2e21d48a9',
    messagingSenderId: '42604918668',
    projectId: 'clippy001-d7445',
    databaseURL: 'https://clippy001-d7445-default-rtdb.firebaseio.com',
    storageBucket: 'clippy001-d7445.appspot.com',
    androidClientId: '42604918668-0ehqg09in2ufnfb2j1vgk5oe7a1gkrr8.apps.googleusercontent.com',
    iosClientId: '42604918668-u6f330622qq19bb26jlddmu8pmlkrj0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.clippy.RunnerTests',
  );
}
